"""Codingan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CD5b2Tv6F91_9wTe8O3h2DUMfINTSYVz
"""

import streamlit as st
import nltk
import string
import random
import re
import io
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pytesseract
import pdfplumber
import cv2

from langdetect import detect
from pdf2image import convert_from_bytes
from reportlab.pdfgen import canvas

from PIL import Image
from pptx import Presentation
from docx import Document
from datetime import datetime

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

# =====================================================
# CONFIG
# =====================================================

st.set_page_config(
    page_title="AI Plagiarism Detector Professional",
    page_icon="🧠",
    layout="wide"
)

# =====================================================
# CSS
# =====================================================

st.markdown("""
<style>

html, body, [class*="css"]{
    font-family: 'Segoe UI', sans-serif;
}

.stApp{
    background: linear-gradient(to bottom right,#0f172a,#1e293b);
    color:white;
}

.title-box{
    background: linear-gradient(90deg,#06b6d4,#2563eb);
    padding:25px;
    border-radius:20px;
    text-align:center;
    margin-bottom:20px;
    box-shadow:0 0 25px rgba(0,0,0,0.4);
}

.title-text{
    font-size:42px;
    font-weight:bold;
    color:white;
}

.subtitle{
    font-size:18px;
    color:white;
}

.kotak{
    background:rgba(255,255,255,0.07);
    padding:20px;
    border-radius:20px;
    margin-bottom:20px;
    border:1px solid rgba(255,255,255,0.1);
}

.stButton>button{
    width:100%;
    height:55px;
    border-radius:15px;
    border:none;
    background:linear-gradient(90deg,#06b6d4,#2563eb);
    color:white;
    font-size:18px;
    font-weight:bold;
}

textarea{
    font-size:15px !important;
}

</style>
""", unsafe_allow_html=True)

# =====================================================
# HEADER
# =====================================================

tanggal = datetime.now().strftime("%d %B %Y")

st.markdown(f"""
<div class="title-box">

<div class="title-text">
🧠 AI Plagiarism Detector Professional
</div>

<div class="subtitle">
Similarity Checker • AI Humanizer • OCR Reader • Academic Rewrite
</div>

<br>

<b>📅 {tanggal}</b>

</div>
""", unsafe_allow_html=True)

# =====================================================
# PEMBUAT
# =====================================================

st.markdown("""
<div class="kotak">

<h3>👨‍💻 Pembuat Website</h3>

1. Arda Valentio Idham<br>
2. Abyan Arif Kurniawan<br>
3. Dieska Ayu Saputri

</div>
""", unsafe_allow_html=True)

# =====================================================
# SESSION
# =====================================================

if "original_texts" not in st.session_state:
    st.session_state.original_texts = {}

if "paraphrase_texts" not in st.session_state:
    st.session_state.paraphrase_texts = {}

if "similarity_matrix" not in st.session_state:
    st.session_state.similarity_matrix = None

# =====================================================
# FILE READER
# =====================================================

def preprocess_image_for_ocr(image):

    img = np.array(image)

    if cv2 is None:
        return img

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2GRAY
    )

    gray = cv2.GaussianBlur(
        gray,
        (3,3),
        0
    )

    thresh = cv2.threshold(
        gray,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )[1]

    return thresh
def baca_file(uploaded_file):

    nama = uploaded_file.name.lower()

    text = ""

    try:

        if nama.endswith(".txt"):

            text = uploaded_file.read().decode("utf-8")

        elif nama.endswith(".pdf"):

          with pdfplumber.open(uploaded_file) as pdf:

             for page in pdf.pages:

              isi = page.extract_text()

              if isi:

                text += isi + "\n"
        elif nama.endswith(".docx"):

            doc = Document(uploaded_file)

            for p in doc.paragraphs:

                text += p.text + "\n"

        elif nama.endswith(".pptx"):

            prs = Presentation(uploaded_file)

            for slide in prs.slides:

                for shape in slide.shapes:

                    if hasattr(shape, "text"):

                        text += shape.text + "\n"

        elif nama.endswith((".png",".jpg",".jpeg")):

            image = Image.open(uploaded_file)

            processed = preprocess_image_for_ocr(image)

            text = pytesseract.image_to_string(
                processed,
                lang="ind"
            )
        if text.strip() == "":

           uploaded_file.seek(0)

           images = convert_from_bytes(
               uploaded_file.read()
        )

        for img in images:

            text += pytesseract.image_to_string(
                img,
                lang="ind"
            )



        return text.strip()

    except Exception as e:

        return f"ERROR : {e}"
def detect_language(text):

    try:

        return detect(text)

    except:

        return "unknown"
# =====================================================
# PREPROCESS
# =====================================================

def preprocess_text(text):

    text = text.lower()

    text = re.sub(r'\d+', ' ', text)

    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    tokens = word_tokenize(text)

    stop_words = set(stopwords.words('indonesian'))
    stop_words.update(stopwords.words('english'))

    filtered = []

    for word in tokens:

        if word not in stop_words and len(word) > 2:

            filtered.append(word)

    hasil = " ".join(filtered)

    if hasil.strip() == "":

        hasil = "dokumen kosong"

    return hasil

# =====================================================
# SYNONYM
# =====================================================

synonym_dict = {

    # --- 1. KONJUNKSI, TRANSISI & PENGHUBUNG LOGIKA ---
        "dan": ["serta", "dan juga", "maupun", "beserta", "beriringan dengan", "termasuk pula", "dan lagi", "tambahan lagi", "maupun juga", "berbarengan dengan"],
        "atau": ["maupun", "ataupun", "atau pun", "pilihan lain", "alternatifnya", "opsi lainnya", "sekiranya", "ataukah"],
        "tetapi": ["namun", "akan tetapi", "namun demikian", "kendati demikian", "sebaliknya", "kontras dengan itu", "namun begitu", "meskipun demikian", "walau demikian", "namun faktanya"],
        "sehingga": ["akibatnya", "maka dari itu", "sebagai dampaknya", "oleh karena itu", "konsekuensinya", "walhasil", "maka terjadilah", "implikasinya", "alhasil", "maka secara otomatis", "yang berujung pada"],
        "karena": ["disebabkan oleh", "mengingat", "berdasarkan alasan", "lantaran", "berhubung", "bermuasal dari", "berakar pada", "sebab", "oleh sebab", "berlandaskan pada alasan"],
        "untuk": ["guna", "demi", "dalam rangka", "bagi", "tujuan", "peruntukan", "orientasi", "kepentingan", "akomodasi", "untuk keperluan"],
        "dengan": ["melalui", "lewat", "secara", "mengacu pada", "berbantuan", "berlandaskan", "mempergunakan", "sarana", "dengan jalan", "menggunakan media"],
        "seperti": ["semisal", "antara lain", "yakni", "selaku", "ibarat", "identik dengan", "sebagai ilustrasi", "berupa", "contohnya", "layaknya", "bagaikan"],
        "selain itu": ["di samping itu", "lebih lanjut", "tambahan pula", "beriringan dengan itu", "lagipula", "bersamaan dengan itu", "seterusnya", "terlepas dari itu", "disamping hal tersebut"],
        "maka": ["oleh sebab itu", "dengan demikian", "akibatnya", "karenanya", "jadinya", "maka dari itu", "hasilnya", "maka secara otomatis", "dengan begitu"],
        "meskipun": ["walaupun", "kendati", "biarpun", "sekalipun", "sungguhpun", "meski", "biarpun demikian", "sekalipun demikian", "meski begitu"],
        "bahwa": ["ialah", "yakni bahwasanya", "bahwa sesungguhnya", "bahwa sanya", "mengenai hal bahwa", "dinyatakan bahwa"],
        "jika": ["apabila", "andai", "kalau", "bilamana", "asalkan", "sekiranya", "dalam hal", "seandainya", "jikalau"],
        "setelah": ["pasca", "seusai", "setelah melewati", "pasca-kejadian", "berikutnya", "setelah usainya", "setelah rampungnya"],
        "sebelum": ["pra", "tadinya", "sebelum adanya", "mendahului", "antisipasi", "sebelum terjadi", "sebelum tibanya"],
        "ketika": ["saat", "kala", "sewaktu", "tatkala", "pada waktu", "di saat", "selama"],
        "namun": ["akan tetapi", "namun demikian", "sebaliknya", "walaupun begitu", "namun begitu", "sekalipun demikian", "kendati begitu"],

        # --- 2. KATA KERJA OPERASIONAL & EKSPRESI INTELEKTUAL ---
        "adalah": ["merupakan", "ialah", "yakni", "merepresentasikan", "didefinisikan sebagai", "tergolong", "menjadi bagian dari", "termasuk", "berwujud", "yakni adalah", "identik dengan"],
        "melakukan": ["melaksanakan", "menjalankan", "menyelenggarakan", "menunaikan", "mengerjakan", "menggelar", "merealisasikan", "mengupayakan", "mempraktikkan", "mengaplikasikan"],
        "menjelaskan": ["menguraikan", "memaparkan", "menjabarkan", "menerangkan", "mendeskripsikan", "menvisualisasikan", "mengeksplanasi", "merinci", "mendefinisikan", "mengomunikasikan", "mengekspos"],
        "menunjukkan": ["mengindikasikan", "membuktikan", "memperlihatkan", "menyatakan", "merefleksikan", "memanifestasikan", "menandakan", "menyingkap", "mengisyaratkan", "menggambarkan"],
        "menggunakan": ["memakai", "memanfaatkan", "menerapkan", "mengimplementasikan", "mengoperasikan", "mendayagunakan", "mengaplikasikan", "memfungsikan", "mendayagunakan", "mengadopsi"],
        "membuat": ["menghasilkan", "menciptakan", "menyusun", "membangun", "merancang", "memformulasikan", "mengonstruksi", "mencetuskan", "mengkreasikan", "menetapkan", "memanufaktur"],
        "meningkatkan": ["mengoptimalkan", "memacu", "memperkuat", "memajukan", "mengakselerasi", "memperbaiki", "mengembangkan", "mendongkrak", "menghebatkan", "menaikkan", "memperluas"],
        "mengurangi": ["meminimalkan", "mereduksi", "menurunkan", "membatasi", "menyusutkan", "memangkas", "mendegradasi", "memitigasi", "meringankan", "menekan"],
        "menemukan": ["mengidentifikasi", "mendeteksi", "memperoleh", "menjumpai", "menemukenali", "mendapati", "menyingkap", "menghasilkan temuan", "memergoki", "mengungkapkan"],
        "memberikan": ["menyajikan", "menyuguhkan", "menyampaikan", "mendistribusikan", "mentransfer", "mengalokasikan", "menghibahkan", "menawarkan", "memberi", "menyumbangkan"],
        "mendukung": ["menunjang", "menyokong", "memfasilitasi", "menguatkan", "memvalidasi", "melegitimasi", "mengukuhkan", "menyokong", "membantu", "membenarkan"],
        "bertujuan": ["dimaksudkan", "berorientasi pada", "bermaksud", "berfokus guna", "bermisi", "berintensi", "ditujukan", "bertarget", "bertitiktolak", "berujung pada"],
        "memiliki": ["mempunyai", "mencakup", "mengandung", "dilengkapi dengan", "memuat", "mengantongi", "terdiri atas", "berbekal", "beroleh", "menyimpan"],
        "membahas": ["mengkaji", "mengulas", "membedah", "mendiskusikan", "menelaah", "menganalisis", "mengevaluasi", "memerinci", "meninjau", "memperdebatkan"],
        "melihat": ["meninjau", "mengamati", "memantau", "memeriksa", "memandang", "mengobservasi", "menatap", "mencermati", "melirik", "menyaksikan"],
        "mengatakan": ["berujar", "menyebutkan", "menuturkan", "mengungkapkan", "menyampaikan", "menandaskan", "menegaskan", "mempermaklumkan", "melisankan", "memproklamirkan"],
        "berubah": ["bertransformasi", "bergeser", "beralih", "bermutasi", "berevolusi", "memodifikasi diri", "berganti", "berfluktuasi", "berinkarnasi"],
        "mencapai": ["meraih", "menggapai", "memperoleh hasil", "memenuhi target", "menggapai puncak", "merealisasikan", "membuahkan", "menembus"],
        "perlu": ["wajib", "mesti", "harus", "layak", "patut", "seyogianya", "fardu", "direkomendasikan", "dituntut"],

        # --- 3. TERMINOLOGI RISET, DATA & METODOLOGI ---
        "penelitian": ["riset", "studi", "kajian ilmiah", "investigasi", "observasi", "eksplorasi", "eksperimen", "analisis ilmiah", "pencarian fakta", "penelaahan", "pemeriksaan ilmiah"],
        "hasil": ["output", "temuan", "simpulan", "perolehan", "konklusi", "produk", "implikasi", "relevansi", "buah pemikiran", "pencapaian", "konsekuensi ilmiah"],
        "metode": ["teknik", "prosedur", "pendekatan", "metodologi", "skema", "strategi", "paradigma", "tata cara", "sistem", "modul", "protokol"],
        "analisis": ["pengkajian", "penelaahan", "pembedahan data  ", "evaluasi", "komputasi", "pemeriksaan", "audit data", "interpretasi", "pembedahan", "disintegrasi data"],
        "sistem": ["mekanisme", "perangkat", "tatanan", "platform", "instansi", "struktur", "ekosistem", "organisasi", "rezim", "susunan"],
        "proses": ["tahapan", "langkah-langkah", "prosedur", "siklus", "alur kerja", "mekanisme kerja", "operasi", "aktivitas", "rangkaian kegiatan"],
        "data": ["informasi", "keterangan", "fakta lapangan", "variabel", "arsip informasi", "basis data", "sekumpulan fakta", "dokumentasi", "input", "rekaman"],
        "sampel": ["contoh", "objek penelitian", "responden", "subjek uji", "perwakilan populasi", "spesimen", "prototipe", "representasi", "model uji"],
        "teori": ["landasan teoretis", "paradigma", "kerangka pemikiran", "postulat", "doktrin", "hipotesis landasan", "dalil", "ajaran", "fondasi konseptual"],
        "masalah": ["kendala", "persoalan", "hambatan", "urgensi", "problematika", "isu", "dilema", "permasalahan", "preparat", "kesulitan", "anomali"],
        "tujuan": ["sasaran", "objektif", "target utama", "destinasi penelitian", "visi", "prioritas", "maksud", "agenda", "iktikad"],
        "dokumen": ["berkas", "arsip", "naskah", "manuskrip", "literatur", "dokumentasi", "tulisan", "surat", "catatan", "instrumen tertulis"],
        "pengguna": ["user", "pemakai", "subjek", "partisipan", "end-user", "klien", "konsumen", "nasabah", "khalayak", "pemangku kepentingan"],
        "pengaruh": ["dampak", "implikasi", "konsekuensi", "imbas", "efek", "residul", "reaksi", "getaran", "intervensi"],
        "hubungan": ["korelasi", "koneksi", "interaksi", "asosiasi", "afiliasi", "relevansi", "pertalian", "jalinan", "matriks"],
        "kemampuan": ["kapabilitas", "potensi", "kompetensi", "kecakapan", "daya", "efikasi", "kredibilitas", "keahlian", "kemahiran"],

        # --- 4. ADJEKTIVA & KETERANGAN  ---
        "penting": ["signifikan", "krusial", "vital", "substansial", "utama", "fundamental", "urgensi", "esensial", "prioritas", "pokok", "mutlak"],
        "baik": ["optimal", "efektif", "unggul", "berkualitas", "prima", "handal", "mumpuni", "bagus", "istimewa", "paten", "terpuji"],
        "sangat": ["amat", "begitu", "secara signifikan", "luar biasa", "ekstrem", "teramat", "istimewa", "betul-betul", "sungguh", "secara substansial"],
        "banyak": ["beragam", "berbagai", "sejumlah besar", "beraneka", "kompleks", "melimpah", "masif", "plural", "berjubel", "berlimpah"],
        "sering": ["kerap", "acapkali", "berulang kali", "intensif", "kontinu", "lazim", "prevalen", "biasa", "terbiasa", "seringkali"],
        "baru": ["mutakhir", "kontemporer", "orisinal", "terkini", "modern", "aktual", "inovatif", "gres", "anyar", "fase baru"],
        "cepat": ["akseleratif", "efisien", "singkat", "sigap", "pesat", "lekas", "responsif", "gesit", "kilat", "instant"],
        "jelas": ["eksplisit", "nyata", "gamblang", "konkret", "terang", "benderang", "transparan", "gamblang", "tegas", "pasti"],
        "sama": ["serupa", "identik", "ekuivalen", "sepadan", "homogen", "paralel", "analog", "setara", "mirip", "seirama"],
        "efektif": ["berdaya guna", "mujarab", "tepat sasaran", "aplikatif", "berhasil guna", "produktif", "fungsional", "tokcer", "mangkus"],
        "akurat": ["presisi", "tepat", "sahih", "valid", "kredibel", "teruji", "reliabel", "eksak", "benar", "cermat"],
        "khusus": ["spesifik", "tertentu", "eksklusif", "partikular", "distingtif", "khas", "istimewa", "terbatas", "spesial"],
        "umum": ["universal", "lazim", "khalayak", "mainstream", "populer", "generik", "publik", "luas", "awam"],
        "kecil": ["minor", "minim", "terbatas", "mikro", "sepele", "insignifikan", "sedikit", "mini", "renik"],
        "besar": ["masif", "luas", "signifikan", "makro", "hebat", "dominan", "agung", "raya", "kolosal"],
        "utama": ["primer", "pokok", "sentral", "dominan", "prioritas", "inti", "kunci", "tulang punggung", "elemen basis"],
        "mudah": ["praktis", "sederhana", "efisien", "user-friendly", "gampang", "enteng", "ringan", "lancar"],
        "sulit": ["kompleks", "rumit", "menantang", "berliku", "payah", "sukar", "terjal", "pelik"],

        # --- 5. SOSIAL, HUKUM, EKONOMI, MEDIS & TEKNIS  ---
        "masyarakat": ["publik", "komunitas", "penduduk", "warga", "populasi", "elemen sosial", "rakyat", "khalayak ramai", "umat"],
        "hukum": ["regulasi", "peraturan", "norma", "perundang-undangan", "ketentuan legal", "hukum positif", "yurisprudensi", "legalitas"],
        "ekonomi": ["finansial", "moneter", "tata niaga", "keuangan", "fiskal", "sektor bisnis", "komersial", "ekonomis", "aspek pasar"],
        "pendidikan": ["edukasi", "pengajaran", "pembelajaran", "pedagogi", "instruksi", "akademik", "studi", "pengkaderan", "didaktik"],
        "negara": ["pemerintah", "kedaulatan", "negeri", "otoritas negara", "bangsa", "republik", "pemerintahan"],
        "global": ["internasional", "mendunia", "menyeluruh", "universal", "lintas batas", "mendunia", "kosmopolitan", "sejagat"],
        "lokal": ["setempat", "domestik", "regional", "pribumi", "kedaerahan", "internal", "insular", "kedaerahan"],
        "perubahan": ["transformasi", "fluktuasi", "pergeseran", "modifikasi", "revisi", "evolusi", "inovasi", "peralihan", "revolusi"],
        "semua": ["seluruh", "segenap", "segala", "totalitas", "keseluruhan", "komprehensif", "semesta", "seisi"],
        "setiap": ["tiap-tiap", "masing-masing", "seluruh", "apapun", "per individu", "saban", "setiap kali"],
        "aplikasi": ["software", "perangkat lunak", "platform", "sistem", "tool", "utilitas", "program", "penerapan", "fasilitas"],
        "teknologi": ["inovasi", "peralatan mutakhir", "sistem digital", "piranti modern", "teknik digital", "mesin", "rekayasa", "mekanisasi"],
        "kesehatan": ["medis", "sanitasi", "higienitas", "kesejahteraan fisik", "klinis", "higienitas"],
        "data_statistik": ["parameter", "distribusi", "variansi", "signifikansi", "probabilitas", "deviasi"],

        # --- 6. WAKTU, TEMPAT & ARAH  ---
        "sekarang": ["saat ini", "masa kini", "dewasa ini", "kontemporer", "pada era ini", "kini", "seketika", "belakangan ini"],
        "dulu": ["sebelumnya", "masa lampau", "terdahulu", "periodik lama", "silam", "lampau", "dahulu kala", "tempo dulu"],
        "depan": ["mendatang", "masa depan", "prospektif", "nanti", "kemudian hari", "hari esok", "hari depan"],
        "kemudian": ["selanjutnya", "berikutnya", "setelah itu", "lalu", "berikutnya", "alkisah", "maka lalu", "seterusnya"],
        "lokasi": ["tempat", "posisi", "letak", "titik koordinat", "area", "medan", "situs", "pos"],

        # --- 7. EMOSI, PSIKOLOGI & EKSPRESI MANUSIA ---
        "senang": ["bahagia", "gembira", "ceria", "riang", "sukacita", "girang", "berbahagia", "lega", "antusias", "sumringah", "bersukacita"],
        "sedih": ["duka", "murung", "nestapa", "galau", "kecewa", "berkabung", "pilu", "sendu", "suram", "terpuruk"],
        "marah": ["geram", "murka", "kesal", "emosi", "berang", "naik pitam", "dongkol", "tersinggung", "gusar", "jengkel"],
        "takut": ["cemas", "khawatir", "ngeri", "gentar", "resah", "waswas", "panik", "ciut", "gelisah", "ketakutan"],
        "bingung": ["bimbang", "galau", "ragu", "linglung", "kalut", "tidak paham", "kebingungan", "tak menentu", "gamang"],
        "percaya": ["meyakini", "mengimani", "menganggap benar", "mempercayai", "berkeyakinan", "beranggapan", "mengafirmasi"],
        "berharap": ["menginginkan", "mendambakan", "mengharapkan", "berangan", "bercita-cita", "memohon", "mendoakan"],
        "cinta": ["kasih sayang", "afeksi", "rasa sayang", "ketertarikan", "kecintaan", "romansa", "perasaan mendalam"],
        "benci": ["muak", "tidak suka", "antipati", "aversi", "menolak", "enggan", "geram terhadap"],
        "tenang": ["damai", "tenteram", "stabil", "kondusif", "kalem", "hening", "nyaman", "relaks"],

        # --- 8. AKTIVITAS SEHARI-HARI ---
        "makan": ["menyantap", "mengonsumsi", "melahap", "menikmati hidangan", "mengudap", "mencicipi"],
        "minum": ["meneguk", "mengonsumsi cairan", "menyeruput", "menghirup", "mencecap"],
        "tidur": ["beristirahat", "terlelap", "merebahkan diri", "tidur pulas", "berbaring"],
        "berjalan": ["melangkah", "berkeliling", "bergerak kaki", "menapaki", "beriring"],
        "berlari": ["berlari cepat", "melaju", "berderap", "berpacu", "bergerak pesat"],
        "belajar": ["menuntut ilmu", "mengkaji", "memahami", "mendalami", "mengenyam pendidikan"],
        "bekerja": ["berkarier", "bertugas", "melaksanakan pekerjaan", "mengabdi", "mencari nafkah"],
        "bermain": ["bersenang-senang", "berekreasi", "berhibur", "mengisi waktu luang", "beraktivitas santai"],
        "berbicara": ["berkomunikasi", "berdialog", "bercakap-cakap", "bertutur", "menyampaikan ucapan"],
        "menulis": ["mencatat", "mengarang", "menyusun tulisan", "menorehkan", "mendokumentasikan"],

        # --- 9. INTERNET, DIGITAL & MEDIA SOSIAL ---
        "internet": ["dunia maya", "jaringan daring", "cyberspace", "web", "ruang digital", "jaringan global"],
        "website": ["situs web", "laman", "portal", "halaman daring", "web page"],
        "komputer": ["PC", "perangkat komputer", "mesin digital", "unit komputasi", "alat elektronik"],
        "handphone": ["ponsel", "smartphone", "gawai", "telepon genggam", "device mobile"],
        "media sosial": ["platform sosial", "jejaring sosial", "sosmed", "komunitas daring", "platform digital"],
        "akun": ["profil", "identitas digital", "user account", "akun pengguna", "akses personal"],
        "password": ["kata sandi", "kode akses", "frasa keamanan", "credential", "PIN keamanan"],
        "unggah": ["upload", "menaikkan file", "mengirim data", "mengunggah berkas"],
        "unduh": ["download", "mengambil data", "mengunduh file", "menarik berkas"],
        "komentar": ["tanggapan", "respon", "opini", "reaksi", "ulasan singkat"],

        # --- 10. BISNIS, KARIER & PEKERJAAN ---
        "bisnis": ["usaha", "perniagaan", "aktivitas komersial", "wirausaha", "industri"],
        "perusahaan": ["korporasi", "firma", "entitas bisnis", "badan usaha", "institusi komersial"],
        "karyawan": ["pegawai", "pekerja", "staf", "tenaga kerja", "personel"],
        "gaji": ["upah", "honor", "penghasilan", "remunerasi", "kompensasi"],
        "keuntungan": ["profit", "laba", "manfaat finansial", "hasil positif", "margin keuntungan"],
        "kerugian": ["rugi", "defisit", "kehilangan", "dampak negatif", "penurunan nilai"],
        "pelanggan": ["konsumen", "customer", "klien", "pembeli", "pemakai jasa"],
        "produk": ["barang", "hasil produksi", "komoditas", "item", "hasil manufaktur"],
        "penjualan": ["sales", "distribusi produk", "aktivitas jual beli", "transaksi penjualan"],
        "pemasaran": ["marketing", "promosi", "branding", "strategi pasar", "advertensi"],

        # --- 11. SAINS, AKADEMIK & ILMIAH ---
        "ilmiah": ["saintifik", "akademis", "berbasis penelitian", "empiris", "rasional"],
        "fakta": ["kenyataan", "realita", "kebenaran", "data valid", "bukti nyata"],
        "hipotesis": ["dugaan sementara", "asumsi penelitian", "prediksi ilmiah", "tesis awal"],
        "variabel": ["parameter", "faktor", "indikator", "unsur penelitian", "komponen"],
        "observasi": ["pengamatan", "monitoring", "peninjauan", "pengawasan", "pemantauan"],
        "eksperimen": ["uji coba", "percobaan", "simulasi", "pengujian", "praktikum"],
        "validasi": ["pengesahan", "verifikasi", "pembuktian", "konfirmasi", "legitimasi"],
        "evaluasi": ["penilaian", "assessment", "review", "analisis hasil", "audit"],
        "kesimpulan": ["simpulan", "konklusi", "intisari", "hasil akhir", "ringkasan hasil"],
        "referensi": ["rujukan", "acuan", "sumber pustaka", "literatur pendukung", "sumber ilmiah"],

        # --- 12. KATA SIFAT TAMBAHAN SUPER LENGKAP ---
        "indah": ["cantik", "elok", "menawan", "memesona", "estetis", "artistik", "rupawan"],
        "buruk": ["jelek", "negatif", "cacat", "tidak baik", "rusak", "suram", "bobrok"],
        "tinggi": ["menjulang", "maksimal", "elevatif", "atas", "superior", "besar"],
        "rendah": ["minimal", "bawah", "inferior", "pendek", "terbatas", "kecil"],
        "panjang": ["memanjang", "lama", "berkepanjangan", "jauh", "luas dimensi"],
        "pendek": ["singkat", "ringkas", "mini", "sebentar", "terbatas"],
        "kuat": ["kokoh", "solid", "perkasa", "tangguh", "stabil", "bertenaga"],
        "lemah": ["rapuh", "tidak kuat", "rentan", "tak berdaya", "melemah"],
        "ramai": ["padat", "hiruk pikuk", "meriah", "penuh aktivitas", "sibuk"],
        "sepi": ["sunyi", "hening", "lengang", "kosong", "minim aktivitas"],

        # --- 13. KATA KERJA TAMBAHAN SUPER BANYAK ---
        "membaca": ["menelaah", "menyimak", "mempelajari", "mengkaji bacaan", "menginterpretasi tulisan"],
        "menghafal": ["mengingat", "memori", "menginternalisasi", "menyimpan dalam ingatan"],
        "mendengar": ["menyimak", "menguping", "mencerap suara", "mendengarkan", "memperhatikan audio"],
        "bertanya": ["mengajukan pertanyaan", "menanyakan", "meminta penjelasan", "menginterogasi"],
        "menjawab": ["merespons", "memberi jawaban", "menanggapi", "memberikan klarifikasi"],
        "memilih": ["menentukan", "menyeleksi", "mengambil keputusan", "menetapkan pilihan"],
        "membeli": ["mengakuisisi", "berbelanja", "mendapatkan", "memperoleh barang"],
        "menjual": ["memasarkan", "mendistribusikan", "menawarkan", "melepas produk"],
        "membuka": ["mengakses", "membentangkan", "mengaktifkan", "memulai"],
        "menutup": ["mengakhiri", "mengunci", "menghentikan", "menyudahi"],

        # --- 14. ALAM, LINGKUNGAN & GEOGRAFI ---
        "bumi": ["planet", "dunia", "jagat raya", "planet biru", "alam semesta"],
        "laut": ["samudra", "perairan", "bahari", "lautan luas", "wilayah maritim"],
        "gunung": ["pegunungan", "bukit tinggi", "dataran tinggi", "lereng"],
        "hutan": ["rimba", "belantara", "kawasan hijau", "vegetasi liar"],
        "cuaca": ["iklim", "atmosfer", "kondisi udara", "situasi meteorologi"],
        "hujan": ["presipitasi", "air turun", "gerimis", "curah hujan"],
        "panas": ["terik", "hangat", "bersuhu tinggi", "membara"],
        "dingin": ["sejuk", "beku", "bersuhu rendah", "adem"],
        "angin": ["hembusan udara", "arus udara", "bayu", "tiupan angin"],
        "matahari": ["surya", "sang surya", "bintang pusat tata surya", "cahaya siang"],

        # --- 15. PEMERINTAHAN & POLITIK ---
        "presiden": ["kepala negara", "pemimpin nasional", "pemegang kekuasaan", "otoritas tertinggi"],
        "pemilu": ["pemilihan umum", "kontestasi politik", "voting nasional", "pesta demokrasi"],
        "politik": ["pemerintahan", "kekuasaan", "strategi negara", "aktivitas kenegaraan"],
        "kebijakan": ["policy", "aturan", "ketetapan", "strategi pemerintah", "regulasi resmi"],
        "menteri": ["pejabat negara", "anggota kabinet", "pemimpin kementerian"],
        "partai": ["organisasi politik", "kelompok politik", "fraksi", "partai pemerintahan"],
        "demokrasi": ["kedaulatan rakyat", "sistem pemilihan", "pemerintahan rakyat"],
        "kampanye": ["promosi politik", "sosialisasi", "propaganda", "aktivitas pemilu"],
        "rakyat": ["masyarakat", "warga negara", "publik", "penduduk"],
        "korupsi": ["penyelewengan", "penyalahgunaan jabatan", "praktik ilegal", "gratifikasi ilegal"],


        # --- 16. TRANSPORTASI & PERJALANAN ---
        "mobil": ["kendaraan roda empat", "otomobil", "alat transportasi", "vehicle", "armada pribadi"],
        "motor": ["sepeda motor", "kendaraan roda dua", "motorbike", "kendaraan bermesin"],
        "pesawat": ["kapal udara", "armada penerbangan", "aircraft", "jet", "alat transportasi udara"],
        "kereta": ["kereta api", "lokomotif", "transportasi rel", "gerbong", "armada rel"],
        "kapal": ["bahtera", "perahu besar", "armada laut", "transportasi maritim"],
        "jalan": ["rute", "lintasan", "akses", "jalur", "arah perjalanan"],
        "perjalanan": ["trip", "ekspedisi", "mobilitas", "pengembaraan", "touring"],
        "terminal": ["stasiun transit", "pusat transportasi", "halte besar", "pusat keberangkatan"],
        "bandara": ["airport", "lapangan udara", "terminal penerbangan", "aerodrome"],
        "macet": ["padat lalu lintas", "kemacetan", "tersendat", "traffic jam", "stagnasi kendaraan"],

        # --- 17. KOMUNIKASI & BAHASA ---
        "bahasa": ["linguistik", "alat komunikasi", "tuturan", "dialek", "bahasa verbal"],
        "kata": ["frasa", "diksi", "ungkapan", "kosakata", "terminologi"],
        "kalimat": ["susunan kata", "ungkapan lengkap", "struktur bahasa", "pernyataan"],
        "cerita": ["kisah", "narasi", "dongeng", "riwayat", "hikayat"],
        "berita": ["informasi terkini", "kabar", "laporan", "news", "warta"],
        "diskusi": ["dialog", "perdebatan", "musyawarah", "forum pembahasan"],
        "pidato": ["orasi", "ceramah", "sambutan", "wejangan", "public speaking"],
        "pesan": ["informasi", "amanat", "message", "komunikasi tertulis"],
        "jawaban": ["respons", "balasan", "klarifikasi", "reaksi", "tanggapan"],
        "pertanyaan": ["inquiry", "kueri", "permintaan penjelasan", "interogasi"],

        # --- 18. KEHIDUPAN SOSIAL & KELUARGA ---
        "keluarga": ["famili", "sanak saudara", "kerabat", "household", "anggota keluarga"],
        "ayah": ["bapak", "orang tua laki-laki", "pater", "figur ayah"],
        "ibu": ["mama", "orang tua perempuan", "bunda", "figur ibu"],
        "anak": ["buah hati", "keturunan", "putra-putri", "generasi penerus"],
        "teman": ["sahabat", "rekan", "kolega", "kawan", "partner"],
        "tetangga": ["warga sekitar", "orang sekitar", "penduduk sekitar"],
        "pernikahan": ["perkawinan", "akad nikah", "ikatan rumah tangga", "marriage"],
        "perceraian": ["perpisahan rumah tangga", "talak", "disolusi pernikahan"],
        "hubungan": ["relasi", "ikatan", "koneksi emosional", "asosiasi"],
        "persahabatan": ["pertemanan", "ikatan sahabat", "hubungan sosial"],

        # --- 19. KEUANGAN & PERBANKAN ---
        "uang": ["dana", "finansial", "mata uang", "nominal", "aset likuid"],
        "bank": ["institusi keuangan", "lembaga finansial", "perbankan", "financial institution"],
        "tabungan": ["simpanan", "saving", "deposito pribadi", "cadangan dana"],
        "pinjaman": ["kredit", "utang", "loan", "pembiayaan"],
        "investasi": ["penanaman modal", "alokasi aset", "capital investment"],
        "hutang": ["utang", "beban finansial", "liabilitas", "pinjaman tertunggak"],
        "pajak": ["tarif negara", "kontribusi wajib", "levy", "beban fiskal"],
        "transaksi": ["aktivitas finansial", "pertukaran", "deal", "kegiatan pembayaran"],
        "harga": ["nilai", "tarif", "biaya", "nominal jual"],
        "murah": ["ekonomis", "terjangkau", "low-cost", "hemat", "bersahabat"],

        # --- 20. MAKANAN & KULINER ---
        "makanan": ["hidangan", "kuliner", "santapan", "menu", "konsumsi pangan"],
        "minuman": ["beverage", "cairan konsumsi", "hidangan cair"],
        "nasi": ["beras matang", "makanan pokok", "hidangan utama"],
        "sayur": ["vegetasi pangan", "olahan hijau", "makanan sehat"],
        "buah": ["hasil tanaman", "produk hortikultura", "fresh fruit"],
        "daging": ["protein hewani", "olahan hewan", "meat"],
        "pedas": ["bercita rasa tajam", "spicy", "berbumbu kuat"],
        "manis": ["berasa gula", "sweet", "bercita rasa manis"],
        "asin": ["bergaram", "salted", "berasa asin"],
        "lezat": ["nikmat", "enak", "sedap", "menggugah selera", "delicious"],

        # --- 21. KESEHATAN & MEDIS TAMBAHAN ---
        "dokter": ["tenaga medis", "praktisi kesehatan", "physician", "tabib"],
        "rumah sakit": ["hospital", "pusat kesehatan", "fasilitas medis"],
        "pasien": ["orang sakit", "subjek medis", "penerima layanan kesehatan"],
        "obat": ["medikasi", "farmasi", "ramuan", "pengobatan"],
        "penyakit": ["gangguan kesehatan", "kelainan medis", "illness", "patologi"],
        "virus": ["mikroorganisme", "agen penyakit", "pathogen"],
        "bakteri": ["mikroba", "organisme mikroskopis", "kuman"],
        "operasi": ["pembedahan", "tindakan medis", "surgery"],
        "perawatan": ["treatment", "pemeliharaan kesehatan", "care"],
        "vaksin": ["imunisasi", "zat kekebalan", "vaccine"],

        # --- 22. PENDIDIKAN & SEKOLAH ---
        "sekolah": ["institusi pendidikan", "lembaga belajar", "akademi"],
        "guru": ["pengajar", "pendidik", "instruktur", "mentor akademik"],
        "murid": ["siswa", "pelajar", "peserta didik", "student"],
        "universitas": ["kampus", "perguruan tinggi", "institusi akademik"],
        "kelas": ["ruang belajar", "tingkatan pendidikan", "kelas akademik"],
        "ujian": ["tes", "evaluasi akademik", "assessment", "exam"],
        "nilai": ["skor", "grade", "hasil evaluasi", "angka akademik"],
        "tugas": ["pekerjaan rumah", "assignment", "aktivitas akademik"],
        "kurikulum": ["silabus", "program pendidikan", "struktur pembelajaran"],
        "beasiswa": ["dukungan pendidikan", "scholarship", "bantuan studi"],

        # --- 23. TEKNOLOGI LANJUTAN & AI ---
        "kecerdasan buatan": ["AI", "artificial intelligence", "mesin cerdas", "sistem pintar"],
        "robot": ["mesin otomatis", "android", "automaton", "robotika"],
        "algoritma": ["alur komputasi", "logika sistem", "formula digital"],
        "program": ["software", "aplikasi", "kode komputer", "sistem digital"],
        "server": ["pusat data", "host", "komputer induk"],
        "database": ["basis data", "penyimpanan data", "bank data"],
        "keamanan": ["proteksi", "security", "perlindungan", "sistem pengamanan"],
        "hacker": ["peretas", "cracker", "pelaku siber"],
        "coding": ["pemrograman", "penulisan kode", "software development"],
        "cloud": ["komputasi awan", "penyimpanan daring", "cloud computing"],

        # --- 24. AGAMA & SPIRITUAL ---
        "agama": ["kepercayaan", "religi", "keyakinan spiritual"],
        "ibadah": ["ritual", "penghambaan", "aktivitas spiritual"],
        "doa": ["permohonan", "munajat", "harapan spiritual"],
        "surga": ["nirwana", "alam bahagia", "tempat suci"],
        "dosa": ["kesalahan spiritual", "pelanggaran agama", "maksiat"],
        "iman": ["kepercayaan", "keyakinan", "faith"],
        "ustaz": ["guru agama", "pendakwah", "penceramah"],
        "masjid": ["tempat ibadah", "surau", "mushola besar"],
        "kitab": ["naskah suci", "buku agama", "wahyu tertulis"],
        "akhirat": ["kehidupan setelah mati", "alam baka", "kehidupan abadi"],

        # --- 25. KATA ABSTRAK ---
        "kehidupan": ["eksistensi", "perjalanan hidup", "realitas hidup", "dinamika manusia"],
        "pengalaman": ["eksperiens", "riwayat kejadian", "memori hidup"],
        "kesempatan": ["peluang", "opportunity", "momentum", "ruang kemungkinan"],
        "tantangan": ["hambatan", "challenge", "ujian", "rintangan"],
        "keberhasilan": ["kesuksesan", "pencapaian", "hasil positif", "triumf"],
        "kegagalan": ["ketidakberhasilan", "failure", "kekalahan", "kemunduran"],
        "motivasi": ["dorongan", "semangat", "stimulus", "inspirasi"],
        "inspirasi": ["motivasi", "ilham", "pemicu ide", "dorongan kreatif"],
        "impian": ["cita-cita", "angan-angan", "harapan besar"],
        "kenangan": ["memori", "ingatan", "nostalgia", "rekaman masa lalu"],

}

# =====================================================
# HUMAN PARAPHRASE
# =====================================================

def human_paraphrase(text):

    paragraphs = text.split("\n")

    hasil_akhir = []

    for paragraph in paragraphs:

        kalimat_list = sent_tokenize(paragraph)

        kalimat_baru_semua = []

        for kalimat in kalimat_list:

            kata_list = kalimat.split()

            baru = []

            for kata in kata_list:

                bersih = re.sub(r'[^\w\s]', '', kata.lower())

                tanda = ''.join(
                    re.findall(r'[^\w\s]', kata)
                )

                if bersih in synonym_dict:

                    pilihan = synonym_dict[bersih]

                    ganti = random.choice(pilihan)

                    baru.append(ganti + tanda)

                else:

                    baru.append(kata)

            random.shuffle(baru)

            kalimat_baru = " ".join(baru)

            kalimat_baru_semua.append(kalimat_baru)

        hasil_akhir.append(
            " ".join(kalimat_baru_semua)
        )

    return "\n".join(hasil_akhir)

# =====================================================
# WORD DOWNLOAD
# =====================================================

def buat_docx(parafrase_dict):

    doc = Document()

    doc.add_heading(
        'HASIL PARAFRASE',
        level=1
    )

    for nama, isi in parafrase_dict.items():

        doc.add_heading(nama, level=2)

        doc.add_paragraph(isi)

    bio = io.BytesIO()

    doc.save(bio)

    bio.seek(0)

   return bio


   def buat_pdf(parafrase_dict):

        buffer = io.BytesIO()

        pdf = canvas.Canvas(buffer)

        y = 800

    pdf.drawString(
        50,
        y,
        "HASIL PARAFRASE"
    )

    y -= 30

    for nama, isi in parafrase_dict.items():

        pdf.drawString(
            50,
            y,
            nama
        )

        y -= 20

        for baris in isi.split("\n"):

            pdf.drawString(
                60,
                y,
                baris[:100]
            )

            y -= 15

            if y < 50:

                pdf.showPage()

                y = 800

    pdf.save()

    buffer.seek(0)

    return buffer

# =====================================================
# UPLOAD
# =====================================================

st.subheader("📂 Upload Maksimal 5 File")

uploaded_files = st.file_uploader(
    "Upload File",
    type=[
        "txt",
        "pdf",
        "docx",
        "pptx",
        "png",
        "jpg",
        "jpeg"
    ],
    accept_multiple_files=True
)

# =====================================================
# SAVE FILE
# =====================================================

if uploaded_files:

    if len(uploaded_files) > 5:

        st.error("❌ Maksimal 5 file")

    else:

        for index, file in enumerate(uploaded_files):

            unique_name = f"{index+1}_{file.name}"

            st.session_state.original_texts[unique_name] = baca_file(file)

# =====================================================
# ANALISIS
# =====================================================

if st.button("🔍 Mulai Analisis"):

    if len(st.session_state.original_texts) < 2:

        st.warning("Upload minimal 2 file")

    else:

        nama_file = list(
            st.session_state.original_texts.keys()
        )

        isi_file = list(
            st.session_state.original_texts.values()
        )

        processed = [
            preprocess_text(x)
            for x in isi_file
        ]

        vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_features=5000
)

        tfidf = vectorizer.fit_transform(processed)

        similarity = cosine_similarity(tfidf)

        st.session_state.similarity_matrix = similarity

        st.success("✅ Analisis Berhasil")

        # =================================================
        # TABEL
        # =================================================

        st.subheader("📊 Tabel Similarity")

        df = pd.DataFrame(
            similarity * 100,
            index=nama_file,
            columns=nama_file
        )

        st.dataframe(
            df.style.format("{:.2f}%"),
            use_container_width=True
        )

        # =================================================
        # HEATMAP
        # =================================================

        st.subheader("🔥 Heatmap Similarity")

        fig, ax = plt.subplots(figsize=(10,8))

        sns.heatmap(
            df,
            annot=True,
            cmap="coolwarm",
            fmt=".1f",
            ax=ax
        )

        st.pyplot(fig)

        # =================================================
        # BAR CHART
        # =================================================

        st.subheader("📈 Grafik Similarity")

        pasangan = []
        nilai = []

        for i in range(len(nama_file)):

            for j in range(i+1, len(nama_file)):

                pasangan.append(
                    f"{i+1} vs {j+1}"
                )

                nilai.append(
                    similarity[i][j] * 100
                )

        fig2, ax2 = plt.subplots(figsize=(12,5))

        bars = ax2.bar(
            pasangan,
            nilai
        )

        for bar in bars:

            y = bar.get_height()

            ax2.text(
                bar.get_x()+bar.get_width()/2,
                y+1,
                f"{y:.1f}%",
                ha='center'
            )

        ax2.set_ylabel("Similarity %")

        st.pyplot(fig2)

        # =================================================
        # PIE CHART
        # =================================================

        tinggi = 0
        rendah = 0

        for v in nilai:

            if v >= 50:
                tinggi += 1
            else:
                rendah += 1

        st.subheader("🥧 Statistik Similarity")

        fig3, ax3 = plt.subplots()

        ax3.pie(
            [tinggi, rendah],
            labels=[
                "≥ 50%",
                "< 50%"
            ],
            autopct='%1.1f%%'
        )

        st.pyplot(fig3)

        # =================================================
        # DETAIL
        # =================================================

        st.subheader("📋 Detail Similarity")

        for i in range(len(nama_file)):

            for j in range(i+1, len(nama_file)):

                persen = similarity[i][j] * 100

                st.markdown(f"""
### 📄 {nama_file[i]}
VS
### 📄 {nama_file[j]}

## 🔍 {persen:.2f}%
""")

                st.progress(int(persen))

                if persen > 70:

                    st.error(
                        "🚨 Minimal parafrase boss 😭"
                    )

                elif persen >= 50:

                    st.warning(
                        "⚠️ Similarity masih tinggi"
                    )

                else:

                    st.success(
                        "✅ Similarity aman"
                    )

# =====================================================
# PARAFRASE CERDAS
# =====================================================

if st.button("✨ Parafrase File Similarity Tinggi"):

    if st.session_state.similarity_matrix is None:

        st.warning("Lakukan analisis terlebih dahulu")

    else:

        similarity = st.session_state.similarity_matrix

        nama_file = list(
            st.session_state.original_texts.keys()
        )

        st.session_state.paraphrase_texts = {}

        target_parafrase = set()

        for i in range(len(nama_file)):

            for j in range(i+1, len(nama_file)):

                persen = similarity[i][j] * 100

                if persen >= 50:

                    target_parafrase.add(
                        nama_file[i]
                    )

                    target_parafrase.add(
                        nama_file[j]
                    )

        for nama, isi in st.session_state.original_texts.items():

            if nama in target_parafrase:

                hasil = isi

                for _ in range(3):

                    hasil = human_paraphrase(
                        hasil
                    )

                st.session_state.paraphrase_texts[
                    nama
                ] = hasil

            else:

                st.session_state.paraphrase_texts[
                    nama
                ] = isi

        st.success(
            "✅ Parafrase selesai"
        )

# =====================================================
# HASIL PARAFRASE
# =====================================================

if st.session_state.paraphrase_texts:

    st.subheader("🤖 Hasil Parafrase")

    for nama in st.session_state.paraphrase_texts:

        st.markdown(f"""
<div class="kotak">

<h3>📄 {nama}</h3>

</div>
""", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:

            st.text_area(
                f"Original {nama}",
                st.session_state.original_texts[nama],
                height=350
            )

        with col2:

            st.text_area(
                f"Hasil Parafrase {nama}",
                st.session_state.paraphrase_texts[nama],
                height=350
            )

# =====================================================
# CEK ULANG
# =====================================================

if st.button("🔄 Cek Similarity Setelah Parafrase"):

    if st.session_state.paraphrase_texts:

        nama_file = list(
            st.session_state.paraphrase_texts.keys()
        )

        isi = list(
            st.session_state.paraphrase_texts.values()
        )

        processed = [
            preprocess_text(x)
            for x in isi
        ]

        vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_features=5000
)

        tfidf = vectorizer.fit_transform(processed)

        similarity = cosine_similarity(tfidf)

        st.subheader(
            "📉 Similarity Setelah Parafrase"
        )

        df2 = pd.DataFrame(
            similarity * 100,
            index=nama_file,
            columns=nama_file
        )

        st.dataframe(
            df2.style.format("{:.2f}%"),
            use_container_width=True
        )

        fig4, ax4 = plt.subplots(figsize=(10,8))

        sns.heatmap(
            df2,
            annot=True,
            cmap="viridis",
            fmt=".1f",
            ax=ax4
        )

        st.pyplot(fig4)

# =====================================================
# DOWNLOAD
# =====================================================

if st.session_state.paraphrase_texts:

    docx_file = buat_docx(
        st.session_state.paraphrase_texts
    )

    st.download_button(

        label="⬇️ Download Hasil Word",

        data=docx_file,

        file_name="hasil_parafrase.docx",

        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    pdf_file = buat_pdf(
         st.session_state.paraphrase_texts
    )

    st.download_button(

       label="⬇️ Download PDF",

       data=pdf_file,

       file_name="hasil_parafrase.pdf",

       mime="application/pdf"
    )

# =====================================================
# FOOTER
# =====================================================

st.markdown("""
<br>

<div style='text-align:center;color:white;'>

AI Plagiarism Detector Professional © 2026

</div>
""", unsafe_allow_html=True)
